name: Nightly PRs to Main

on:
  workflow_dispatch:
    inputs:
      dryrun:
        default: false
        type: boolean
        description: Dry Run
  workflow_run:
    workflows: [Nightly Submodule Update]
    types: [completed]

jobs:
  Nightly_PRs_to_Main:
    uses: 51Degrees/common-ci/.github/workflows/nightly-prs-to-main.yml@nightly-pipeline
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}

