name: Nightly PRs to Main

on:
  workflow_dispatch:
    inputs:
      dryrun:
        default: 'false'
        description: Dry Run
    # schedule:
    #   - cron: '0 1 * * *'

jobs:
  Nightly_PRs_to_Main:
    uses: postindustria-tech/common-ci/.github/workflows/nightly-prs-to-main.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      asset-keys: '{"TestResourceKey": "${{ secrets.SUPER_RESOURCE_KEY}}"}'

